# Generated by Django 5.1.6 on 2025-02-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='articles',
        ),
    ]
